import type { CardAsset } from "$components/cards/GameCard.svelte";
import type { CardDetail } from "$types/card.type";
import { queryCatalog, type CatalogCard, type CardQuery } from "$utils/cards/card-query";
import { AdapterClass } from "./classes/adapter.class";
import { CreatureAdapter, type IGameCreature } from "./creature.adapter";

// The static SPA has no server, so card data is read from the prebuilt catalog
// (static/cards/catalog.json, generated by the data package's
// build-card-catalog on each build) and filtered in the browser via the shared
// queryCatalog logic — the same code path in dev and prod. Fetched once and
// memoised for the lifetime of the tab.
let catalogPromise: Promise<CatalogCard[]> | null = null;

function loadCatalogData(): Promise<CatalogCard[]> {
	if (!catalogPromise) {
		// Cache-bust so a rebuilt catalog (e.g. after saving card positioning/effects
		// on /cards) is picked up on the next page load rather than a stale
		// browser-cached copy. The catalog is memoised per tab below, so this is one
		// fetch per session, not per query.
		catalogPromise = fetch(`/cards/catalog.json?t=${Date.now()}`, { cache: 'no-store' })
			.then((res) => {
				if (!res.ok) throw new Error(`Could not load card catalog (${res.status})`);
				return res.json();
			})
			.then((data) => (data?.cards ?? []) as CatalogCard[])
			.catch((err) => {
				// Let the next call retry rather than caching the failure forever.
				catalogPromise = null;
				throw err;
			});
	}
	return catalogPromise;
}

// Drop the memoised catalog so the next loadCatalogData() re-fetches from disk.
// Called after the catalog is rebuilt on the server (e.g. saving card positioning
// or effect assignments on /cards): without this the tab keeps serving the
// snapshot taken on first load, so a client-side navigation to the board renders
// from pre-save data and the customizations appear to have no effect.
export function invalidateCatalog(): void {
	catalogPromise = null;
}

export class CardApiAdapter extends AdapterClass {
    limit = 100
    loading = false
    totalCards = 0
	page = 0
    creatureAdapter = new CreatureAdapter()
    cards: IGameCreature[] = []

    constructor(){
        super('card-api-adapter')
    }

    async load(p: number, q: string = '', type: string = 'all', attr: string = 'all', race: string = 'all', billboard: boolean = false) {
		this.loading = true;
			const query: CardQuery = {
				limit: this.limit,
				offset: (p - 1) * this.limit,
				q,
				type,
				attribute: attr,
				race,
				billboard
			};

			const catalog = await loadCatalogData();
			const data = queryCatalog(catalog, query);
			this.cards = data.cards.filter((c) => c.lvl).map((c) => this.creatureAdapter.getAttributes(c))
			this.totalCards = data.total;

			if (p === 1) {
				this.page = 1;
			}

            return {
                availableTypes: data.availableTypes,
                availableAttributes: data.availableAttributes,
                availableRaces: data.availableRaces
            }

    }

    // Load a page of the raw card catalog (monsters *and* non-monsters) plus the
    // filter facets, without converting to creatures. Monsters only appear once
    // they have a cutout (billboard); every other card type always shows.
    // Card types are filtered as a top-level `category` (monster/spell/trap) plus
    // a `subType` sub-categorization within it (monster variety, or spell/trap race).
    async loadCatalog(
        p: number,
        q: string = '',
        category: string = 'all',
        subType: string = 'all',
        attr: string = 'all',
        race: string = 'all'
    ) {
        const query: CardQuery = {
            limit: this.limit,
            offset: (p - 1) * this.limit,
            q,
            category,
            subType,
            attribute: attr,
            race,
            monsterCutout: true
        };

        const catalog = await loadCatalogData();
        const data = queryCatalog(catalog, query);

        return {
            cards: data.cards as CardAsset[],
            total: data.total,
            availableAttributes: data.availableAttributes,
            availableRaces: data.availableRaces,
            monsterTypes: data.monsterTypes,
            spellTypes: data.spellTypes,
            trapTypes: data.trapTypes
        };
    }

    // Browse only the cards that belong to the saved decks, distinct by id, with
    // the same filter/pagination UI the full catalog uses. `deckCardIds` is the
    // union of every deck's enabled card ids, so every card contained in a deck is
    // in scope — this mirrors the full-catalog browser (loadCatalog) exactly, only
    // narrowed to the decks' cards, so spells and traps show regardless of whether
    // they're "playable", the same as the unrestricted browser did. The catalog
    // holds one entry per id, so restricting to the id set is inherently
    // deduplicated. Facets and pagination are computed over that restricted set, so
    // the filter dropdowns only offer values present in the decks. As on the full
    // catalog, monsters only surface once they have a cutout (billboard) prepared
    // for the board.
    async loadDeckCatalog(
        deckCardIds: number[],
        p: number = 1,
        q: string = '',
        category: string = 'all',
        subType: string = 'all',
        attr: string = 'all',
        race: string = 'all'
    ) {
        const uniqueIds = [...new Set(deckCardIds)];
        if (!uniqueIds.length) {
            return {
                cards: [] as CardAsset[],
                total: 0,
                availableAttributes: [] as string[],
                availableRaces: [] as string[],
                monsterTypes: [] as string[],
                spellTypes: [] as string[],
                trapTypes: [] as string[]
            };
        }

        const catalog = await loadCatalogData();
        // Restrict to the deck-derived cards — one entry per id, every card the
        // decks contain (no playable filter; the full-catalog browser had none).
        // Spell and Trap cards are excluded outright, so the /cards browser only
        // shows monsters; dropping them here also empties the spell/trap facets.
        const restricted = queryCatalog(catalog, { ids: uniqueIds }).cards.filter(
            (card) => card.type !== 'Spell Card' && card.type !== 'Trap Card'
        );

        // Apply the UI filters + pagination over just those cards. Monsters only
        // surface once they have a cutout (billboard) prepared for the board.
        const data = queryCatalog(restricted, {
            limit: this.limit,
            offset: (p - 1) * this.limit,
            q,
            category,
            subType,
            attribute: attr,
            race,
            monsterCutout: true
        });

        return {
            cards: data.cards as CardAsset[],
            total: data.total,
            availableAttributes: data.availableAttributes,
            availableRaces: data.availableRaces,
            monsterTypes: data.monsterTypes,
            spellTypes: data.spellTypes,
            trapTypes: data.trapTypes
        };
    }

    // Resolve a list of card ids into their raw card assets, preserving the order
    // they appear in and keeping duplicates so deck copy counts survive. Only
    // playable cards come back: vanilla monsters, plain Effect Monsters, and
    // Fusion/Ritual monsters, plus any other card (remaining gimmick monster,
    // spell, or trap) that has an effect assigned — the `playable` filter drops
    // the remaining special-summon monsters and effectless spell/traps. Used to
    // render a deck's full contents through the shared CardTile renderer.
    async loadCardAssetsByIds(ids: number[], forcedIds: number[] = []): Promise<CardAsset[]> {
        const uniqueIds = [...new Set(ids)];
        if (!uniqueIds.length) return [];

        const catalog = await loadCatalogData();
        const data = queryCatalog(catalog, {
            ids: uniqueIds,
            playable: true,
            // Forced ids override the playable verdict for this deck's cards.
            force: [...new Set(forcedIds)]
        });

        const byId = new Map<number, CardAsset>();
        for (const c of data.cards as CardAsset[]) byId.set(c.id, c);

        return ids.map((id) => byId.get(id)).filter((c): c is CardAsset => Boolean(c));
    }

    // Resolve a list of card ids into every card that exists in the local DB,
    // preserving order and duplicates, each tagged with whether it is `playable`
    // (the same vanilla-monster / assigned-effect rule the deck previews apply).
    // Cards missing from the DB are dropped; cards that exist but are not playable
    // come back with `playable: false` so the deck editor can render them disabled
    // instead of hiding them.
    async loadDeckEditorCards(
        ids: number[]
    ): Promise<Array<{ card: CardAsset; playable: boolean }>> {
        const uniqueIds = [...new Set(ids)];
        if (!uniqueIds.length) return [];

        const catalog = await loadCatalogData();
        const all = queryCatalog(catalog, { ids: uniqueIds });
        const playable = queryCatalog(catalog, { ids: uniqueIds, playable: true });

        const byId = new Map<number, CardAsset>();
        for (const c of all.cards as CardAsset[]) byId.set(c.id, c);
        const playableIds = new Set<number>(playable.cards.map((c) => c.id));

        return ids
            .map((id) => byId.get(id))
            .filter((c): c is CardAsset => Boolean(c))
            .map((card) => ({ card, playable: playableIds.has(card.id) }));
    }

    // Load the complete record for a single card, with every field available in
    // the source data. Used only by the /admin card detail modal (dev-only
    // tooling, stripped from the production build), so it reads the full record
    // from the /database/cards/[id] endpoint — which serves the data
    // package's cardinfo.json off disk — rather than the trimmed catalog. That
    // source file lives outside static/, so it is never fetchable as a plain asset.
    async loadDetail(id: number): Promise<CardDetail> {
        const res = await fetch(`/database/cards/${id}`);
        if (!res.ok) throw new Error(`Could not load card ${id} (${res.status})`);
        const data = await res.json();
        const card = data?.card as CardDetail | undefined;
        if (!card) throw new Error(`Card ${id} not found`);
        return card;
    }

    // Resolve a list of card ids (e.g. the player's deck) into monster
    // creatures, preserving the order they appear in and skipping duplicates
    // and non-monster cards. Pass `playableOnly` to also apply the `playable`
    // filter, so only playable creatures (vanilla monsters, plain Effect
    // Monsters, Fusion/Ritual monsters, and remaining gimmick monsters with an
    // assigned effect) come back (used by the board, which only summons playable
    // creatures).
    async loadByIds(
        ids: number[],
        playableOnly = false,
        forcedIds: number[] = []
    ): Promise<IGameCreature[]> {
        this.loading = true;
        try {
            const uniqueIds = [...new Set(ids)];
            if (!uniqueIds.length) {
                this.cards = [];
                return this.cards;
            }

            const query: CardQuery = { ids: uniqueIds };
            if (playableOnly) {
                query.playable = true;
                // Forced ids override the playable verdict for this deck's cards.
                query.force = [...new Set(forcedIds)];
            }
            const catalog = await loadCatalogData();
            const data = queryCatalog(catalog, query);

            const byId = new Map<number, CardAsset>();
            for (const c of data.cards as CardAsset[]) byId.set(c.id, c);

            this.cards = uniqueIds
                .map((id) => byId.get(id))
                .filter((c): c is CardAsset => Boolean(c?.lvl))
                .map((c) => this.creatureAdapter.getAttributes(c));

            return this.cards;
        } finally {
            this.loading = false;
        }
    }
}
